### PR TITLE
🔖 Complete Workbook: Tenzies

### PR DESCRIPTION
**Pull request by d-a-ve**
Project Description:
A React game where you roll 10 dice until all the dice are the same

Field:
Web Development

Difficulty:
Beginner

Name and Handles:
[Aronmwan Dave](https://github.com/d-a-ve/) (daveee.ee#3952)

### CODE REVIEW

**Comment by d-a-ve** [comment]
Hi @xyntechx, I have completed the changes and additions. Please help review. Also let me know if there's an issue with the merge because this was my first time solving merge conflicts.

Thank you.

**Comment by xyntechx** [comment]
Hi @d-a-ve! Thank you so much for the additions! To resolve the conflicts more easily, perhaps you can sync your fork with the current NexLiber main branch, and then add your additions after that. That way, the merge conflicts will disappear (hence easier to resolve). Thank you for the trouble!

**Comment by d-a-ve** [comment]
Oh wow, I didn't think of that. Thank you @xyntechx, I can't wait for ver. 2.0

**Comment by xyntechx** [comment]
@d-a-ve let me know when you're done :))

**Comment by d-a-ve** [comment]
@xyntechx I had already solved the merge conflicts before I made the PR.
Or is there an issue? Because I am not seeing any from my end.

**Comment by xyntechx** [comment]
@d-a-ve I see these

Screenshot_20230201_132625_Chrome
Screenshot_20230201_132636_Chrome

**Comment by d-a-ve** [comment]
@xyntechx Alright, thanks. Let me see what's wrong

**Pull request closed without merging**
