### PR TITLE
🔖 Complete Workbook: Tenzies

### PR DESCRIPTION
**Pull request by d-a-ve**
Project Description:
A React game where you roll 10 dice until all the dice are the same

Field:
Web Development

Difficulty:
Beginner

Name and Handles:
[Aronmwan Dave](https://github.com/d-a-ve/) (daveee.ee#3952)

### CODE REVIEW

**Review by xyntechx — CHANGES_REQUESTED** [review]
Hi @d-a-ve! Thank you for the Workbook. I have one question before we can merge this Workbook:
You wrote "Before we start coding, let's clean up our folder and only leave the files we need. So after clean up, the folder sturcture will be like this" but didn't specify what the folder structure should be. Can you clarify this paragraph please?

Just fyi, to prevent the `Warning: Each child in an array should have a unique key prop` message, you can simply pass the index of the element from the `map` function instead of installing `nanoid`. This is a simpler solution. You don't have to change your Workbook though; it's good that the Learners are exposed to new libraries/packages.

**Comment by d-a-ve** [comment]
> Hi @d-a-ve! Thank you for the Workbook. I have one question before we can merge this Workbook:
> You wrote "Before we start coding, let's clean up our folder and only leave the files we need. So after clean up, the folder sturcture will be like this" but didn't specify what the folder structure should be. Can you clarify this paragraph please?
> 
> Just fyi, to prevent the `Warning: Each child in an array should have a unique key prop` message, you can simply pass the index of the element from the `map` function instead of installing `nanoid`. This is a simpler solution. You don't have to change your Workbook though; it's good that the Learners are exposed to new libraries/packages.


Thank you for the review @xyntechx .

So for the first observation, I actually have a picture for how the structure to be but I didn't know where to put it that's why I left that part blank. In the code I actually left a comment to put the image later on, I was going to ask you how I can go about it.

For the second, I didn't use the index because the react docs advised not to use it that it can cause some unexpected complications. So I opted to use the nanoid.

**Comment by xyntechx** [comment]
@d-a-ve ah okay! You can send me the image via this chat and I'll include it in the Workbook for you. Thanks!

**Review by xyntechx — APPROVED** [review]

**Comment by d-a-ve** [comment]
Thank you @xyntechx, I am currently making some additions and changes to the workbook so I was going to push this again after it looks better.

**Comment by xyntechx** [comment]
Ah okay no worries! You can still push the changes and we'll get the updates published!

**Pull request merged**
